import { ScreenRect } from "../constants/nodeElm.js";

export const mockCoinAPI = [
    {
        id: "coin-1",
        x: ScreenRect.width() + 10,
        y: ScreenRect.height() / 2,
        width: 20,
        height: 20,
        speedX: 9,
    },
    {
        id: "coin-2",
        x: ScreenRect.width() + 40,
        y: ScreenRect.height() / 2,
        width: 20,
        height: 20,
        speedX: 8,
    },
    {
        id: "coin-3",
        x: ScreenRect.width() + 70,
        y: ScreenRect.height() / 2,
        width: 20,
        height: 20,
        speedX: 7,
    },
    {
        id: "coin-4",
        x: ScreenRect.width() + 100,
        y: ScreenRect.height() / 2,
        width: 20,
        height: 20,
        speedX: 6,
    },
    {
        id: "coin-5",
        x: ScreenRect.width() + 190,
        y: ScreenRect.height() / 2,
        width: 20,
        height: 20,
        speedX: 5,
    },
    {
        id: "coin-6",
        x: ScreenRect.width() + 210,
        y: ScreenRect.height() / 2,
        width: 20,
        height: 20,
        speedX: 6,
    },
    {
        id: "coin-7",
        x: ScreenRect.width() + 240,
        y: ScreenRect.height() / 2,
        width: 20,
        height: 20,
        speedX: 8,
    },
    {
        id: "coin-8",
        x: ScreenRect.width() + 240,
        y: ScreenRect.height() / 2 - 100,
        width: 20,
        height: 20,
        speedX: 2,
    },
    {
        id: "coin-9",
        x: ScreenRect.width() + 240,
        y: ScreenRect.height() / 2 - 30,
        width: 20,
        height: 20,
        speedX: 10,
    },
    {
        id: "coin-11",
        x: ScreenRect.width() + 240,
        y: ScreenRect.height() / 2 - 20,
        width: 20,
        height: 20,
        speedX: 5,
    },
    {
        id: "coin-10",
        x: ScreenRect.width() + 240,
        y: ScreenRect.height() / 2 + 70,
        width: 20,
        height: 20,
        speedX: 5,
    },
    {
        id: "coin-12",
        x: ScreenRect.width() + 240,
        y: ScreenRect.height() / 2 + 120,
        width: 20,
        height: 20,
        speedX: 4,
    },
    {
        id: "coin-13",
        x: ScreenRect.width() + 240,
        y: ScreenRect.height() / 2 + 100,
        width: 20,
        height: 20,
        speedX: 8,
    },
    {
        id: "coin-14",
        x: ScreenRect.width() + 240,
        y: ScreenRect.height() / 2 + 20,
        width: 20,
        height: 20,
        speedX: 8,
    },
];
